// modules/documentReader.js

const fs = require('fs').promises;
const path = require('path');
const Sentry = require('@sentry/node');
const pdf = require('pdf-parse');
const mammoth = require('mammoth');

const logger = require('../utils/logger');

const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5 MB
const MAX_TEXT_LENGTH = 15000; // Character limit for AI to prevent token limit issues
const SUSPICIOUS_EXTENSIONS = ['.exe', '.bat', '.sh', '.js', '.py', '.msi', '.dll', '.vbs'];

/**
 * Reads a file, extracts its text, and returns it for summarization using generateAIResponse.
 * @param {string} filePath - Path to the file to be processed.
 * @param {object} msg - Original message object from Telegram for context.
 * @param {object} aiDependencies - Object containing { generateAIResponse, USER_NAME, Mood }.
 * @returns {Promise<string>} Document summary generated by AI.
 */
async function summarizeDocument(filePath, msg, aiDependencies) {
    try {
        const stats = await fs.stat(filePath);
        const fileExt = path.extname(filePath).toLowerCase();

        // Security Check for File Extension & Size
        if (SUSPICIOUS_EXTENSIONS.includes(fileExt)) {
            throw new Error(`File type ${fileExt} is not allowed for security reasons.`);
        }
        if (stats.size > MAX_FILE_SIZE) {
            throw new Error(`File size ${stats.size} exceeds the 5MB limit.`);
        }

        logger.info(
            { event: 'file_processing_start', file: filePath, size: stats.size },
            'Starting document processing.',
        );

        // Extract Text Based on File Type
        let text = '';
        switch (fileExt) {
            case '.pdf':
                const dataBuffer = await fs.readFile(filePath);
                const data = await pdf(dataBuffer);
                text = data.text;
                break;
            case '.docx':
                const docxResult = await mammoth.extractRawText({ path: filePath });
                text = docxResult.value;
                break;
            case '.txt':
            case '.csv':
            case '.md':
                text = await fs.readFile(filePath, 'utf-8');
                break;
            default:
                throw new Error(`Unsupported file type: ${fileExt}`);
        }

        logger.info({ event: 'text_extraction_success', length: text.length }, 'Text extracted successfully.');

        // Truncate text if it's too long
        let processedText = text;
        if (text.length > MAX_TEXT_LENGTH) {
            processedText = text.substring(0, MAX_TEXT_LENGTH) + '\n\n[...text truncated because it is too long...]';
            logger.warn(
                { event: 'text_truncated', original: text.length, new: processedText.length },
                'Text truncated due to length limit.',
            );
        }

        // Get required functions and data from dependencies
        const { generateAIResponse, USER_NAME, Mood } = aiDependencies;

        // Create a specific prompt for summarization task, which will be the 'user' input for generateAIResponse.
        // This prompt instructs the AI to act as Lumina but with a specific task.
        // The system prompt from generateAIResponse will still handle her personality.
        const summaryUserPrompt =
            '[Document Context] The user just sent a document. Analyze it ' +
            'and help the user with the content provided. If no specific context is given, ' +
            `summarize the document.\n\nHere is the text:\n\n---\n\n${processedText}`;

        logger.info(
            { event: 'summarization_start_with_ai_response' },
            'Sending document text to generateAIResponse for summarization.',
        );

        // Call generateAIResponse with appropriate arguments
        const summary = await generateAIResponse(
            summaryUserPrompt,
            msg.chat.id,
            { topic: 'document_summary' }, // messageContext
            USER_NAME,
            Mood,
        );

        logger.info(
            { event: 'summarization_success_with_ai_response' },
            'Successfully received summary via generateAIResponse.',
        );
        return summary;
    } catch (error) {
        logger.error(
            { event: 'document_processing_error', error: error.message, stack: error.stack },
            'An error occurred in summarizeDocument.',
        );
        Sentry.captureException(error);
        // Re-throw the error so it can be caught by the handler
        throw error;
    } finally {
        // Auto-delete file
        try {
            await fs.unlink(filePath);
            logger.info({ event: 'file_cleanup_success', file: filePath }, 'Temporary file deleted successfully.');
        } catch (unlinkError) {
            logger.error(
                { event: 'file_cleanup_error', error: unlinkError.message, file: filePath },
                'Failed to delete temporary file.',
            );
            Sentry.captureException(unlinkError);
        }
    }
}

module.exports = { summarizeDocument };